[Interface]
PrivateKey = <PrivateKey_of_Client>
# IP Address of the client in vpn network --> have to be in defined ip range of the vpn server
Address = 10.10.0.2/24
# important to connect the internet through the vpn-server
DNS = 1.1.1.1

[Peer]
PublicKey = <vpn-server public key>
# Allow each ipv4 and ipv6 to connect from vpn server
AllowedIPs = 0.0.0.0/0, ::/0
# don´t care wich public port is select, important is the forwarding port to vpn server 51820/udp in Router
Endpoint = <router_public-IP or Domain>:<public_port_router>
PersistentKeepalive = 25