[Interface]
# define IP Address of the vpn server and the ip-range in vpn network 10.10.0.1 - 10.10.0.256
Address = 10.10.0.1/24
# UDP Port from wireguard vpn server
ListenPort = 51820
PrivateKey = <server_private_key>

# Definition of Routing --> find out the correct network interface enp0s3; eth0; ens18 ...
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT
PostUp = iptables -A FORWARD -o wg0 -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o enp0s3 -j MASQUERADE

PostDown = iptables -D FORWARD -i wg0 -j ACCEPT
PostDown = iptables -D FORWARD -o wg0 -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o enp0s3 -j MASQUERADE

# Peer Client 1:
[Peer]
PublicKey = <public_key_client_1>
# IP Address Client, must be the same as in the client.conf
AllowedIPs = 10.10.0.2/32

# Peer Client 2:
[Peer]
PublicKey = <public_key_client_2>
# IP Address Client, must be the same as in the client.conf
AllowedIps = 10.10.0.3/32